### ISSUE TITLE
As a coordinator I want to be able to give a Variant assigned volunteer the Variant Proficiency aptitude

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/community-curation#29]
- [ ] Review workflow with Courtney
- [ ] Add button to assignments/aptitudes view/form

**Comment by yugen** [comment]
@courtneythaxton @lizzkearns Will there be an attestation related to Variant Proficiency?  If so can you please send me the attestation?

Thanks!

**Comment by lizzkearns** [comment]
@yugen @courtneythaxton Yes, here is the link to the variant curator attestation: https://docs.google.com/forms/d/e/1FAIpQLSctUQSSiQ3RZ-lJKQrsV6XhxYLMALO4j-U1qkl9pWL0TTsJrw/viewform

**Comment by yugen** [comment]
Thanks, @lizzkearns!

**Comment by yugen** [comment]
@lizzkearns This looks like the same attestation I have for Basic Variant.  Should someone who's already completed the Basic Variant attestation do this attestation again for the advanced level?

@courtneythaxton if you have more info, please let me know.

**Comment by courtneythaxton** [comment]
Hi @yugen Variant Level 2 individuals do not have another attestation.

They will require a specific n umber of variants that are approved by their coordinator or some level of documentation in order to be considered a sustained variant curator.

I actually wonder if for some aspect of this, we should possibly hold off for level 2 training as this brings into the picture the training for the ClinGen personnel. At which point if a Comprehensive variant volunteer has stayed on the group, they may transition as a formal member. This way the tracking at this level could be done on this larger ticket.

Hopefully that makes sense!

I think we can maybe set this on the back burner a bit until I talk with the C3 again!
