### ISSUE TITLE
As a coordinator, I want to be able to give a Baseline volunteer the Genetic Evidence aptitude

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/community-curation#30]
- [ ] Review workflow with Courtney.
- [ ] Add button to assignments form to start process.

**Comment by yugen** [comment]
@courtneythaxton @lizzkearns Will there be an attestation related to Baseline Genetic evidence?  If so can you please send me the attestation?

Thanks!

**Comment by lizzkearns** [comment]
@yugen @courtneythaxton An attestation for Baseline curators has not been created yet but I believe there will be one. Courtney is that correct?

**Comment by courtneythaxton** [comment]
Hi @yugen and @lizzkearns 

Yes we will have an attestation. Now that the world has turned upside down, the C3 wants to think about how we will institute training for Baseline, with potential webinars, so I want to get a handle on this for the attestation. 

I can certainly come up with some of the items, as long as we were able to add more items to attest to in the future, otherwise I may wait a bit.

**Comment by courtneythaxton** [comment]
@yugen, I actually had created a Baseline Attestation (Feb 26, 2020), I thought I had emailed it, but maybe not! Here it is!
[Baseline Annotation Attestation_v1.docx](https://github.com/clingen-data-model/community-curation/files/4411147/Baseline.Annotation.Attestation_v1.docx)

This would be a nice start, if we have the ability to add in the future?

**Comment by yugen** [comment]
@courtneythaxton This looks like the same attestation we're giving for Baseline Basic Evidence.  Is there a different one for Genetic evidence, should they re-do the same attestation, or is there not an attestation required for Genetic Evidence?

**Comment by courtneythaxton** [comment]
@yugen I was at least able to see the option to assign a volunteer to baseline basic evidence or baseline genetic evidence, so that looks nice.
