### ISSUE TITLE
Sort volunteers by EP

### ISSUE THREAD

**Issue by lizzkearns** [clingen-data-model/community-curation#39]
When you sort the volunteers by "Expert Panel" and choose "Mitochondrial Disease" it comes up with 2 individuals that have been assigned to that GCEP/VCEP as well as three individuals that don't seem to have any relation to the GCEP or VCEP - they are not in the EP nor have they requested to be placed in the EP.

**Comment by yugen** [comment]
@lizzkearns It looks like the three folks showing up were assigned to the Mitochondrial Diseases GCEP when they were imported b/c the spreadsheet lists them as assigned to Variant Pathogenicity / "Mito".  My guess is that because we don't have a "Mito" expert panel I mapped "Mito" to "Mitochondrial Diseases GCEP".

You're not seeing the Mitochondrial Disease GCEP assignment in the web interface because it's an "orphan" assignment.  In the database each EP assignment is a child of a Curation Activity assignment and are loaded into the interface in that hierarchy.  Because these three EP assignments don't have a corresponding parent Curation Activity assignment they don't get loaded into the interface.  In the normal course of using the system you shouldn't be able to create orphan assignments.

So, how do we fix this?  We probably need to add the appropriate Variant / Mito expert panel to the database and update the import script to assign these three volunteers to that EP.

If you give me the official name of that EP I'll take care of it?

**Comment by lizzkearns** [comment]
@yugen Ok, that makes sense! The official name of the EP is Mitochondrial Diseases VCEP. Thanks!

**Comment by yugen** [comment]
@lizzkearns Done!  Changes are reflected in the demo system.  Thanks for finding this!
